
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: /swagger-ui-custom.html
  swagger-ui:
    operations-sorter: method
server:
  port: 8080
